//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public Credential()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public System.Guid Employee_ID { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
